### ISSUE TITLE
Set ntp upstream server

### ISSUE THREAD

**Issue by eccles** [geerlingguy/ansible-role-ntp#1]
Add support for specifying upstream NTP servers (as a list) in the ntp.conf file.

This is useful for large datacenters which have a local NTP machine.

ntp_servers: [ ntp1.local.domain, ntp2.local.domain, ntp3.local.domain, ]

**Comment by kadecole** [comment]
Just submitted a merge request with this addition.

**Comment by kostyrevaa** [comment]
Is this ever gonna be merged?

**Comment by geerlingguy** [comment]
This was merged in #5.
