### ISSUE TITLE
ansible_managed tag causes ntp restart every run

### ISSUE THREAD

**Issue by gregretkowski** [geerlingguy/ansible-role-ntp#11]
Hi!

This library has been working great for me to manage my ntp configs; thanks for writing it. There's one thing that's annoying me - that is on every run ntp is restarted because of the inclusion of the ansible_managed tag in the top of the file, which has a different timestamp, and so different file contents every time ansible is run:

https://github.com/geerlingguy/ansible-role-ntp/blob/1420529abcdda64e1f63df142d3b99e71abf43ed/templates/ntp.conf.j2#L1

Would you accept a PR which removes ansible_managed from that line and instead adds a simple unchanging comment that the file is managed by Ansible?

**Comment by pgporada** [comment]
@gregretkowski 
You can override the ansible_managed via ansible.cfg. https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg

Having the time/date in ansible.cfg breaks idempotency for me as well. I use a simple "Ansible manages this and your changes will be stomped" line.

**Comment by gregretkowski** [comment]
So could I make a PR which just replaces that line with 'Ansible manages this and your changes will be stomped' ?

**Comment by pgporada** [comment]
@gregretkowski 
You can use a custom ansible.cfg in each of your projects such as this. https://github.com/pgporada/ansible-playbook-homerouter/blob/master/ansible/ansible.cfg

**Comment by geerlingguy** [comment]
This is also fixed upstream—now the default is not an ever-changing value.
