### ISSUE TITLE
Debian 12 /etc/timezone inconsistent with current timezone

### ISSUE THREAD

**Issue by websafe** [geerlingguy/ansible-role-ntp#132]
Hello,

I have installed Debian 12 using the `Europe/Warsaw` timezone and configured the host using `ntp_timezone=US/Eastern`.

And then I've noticed the following:

 - `/etc/localtime` points to `/usr/share/zoneinfo/US/Eastern` - OK, as expected,
 - `date` returns `EST` - OK, as expected,
 - `/etc/timezone` still contains `Europe/Warsaw` - **inconsistent / unexpected**.

Should I worry about this?

I have found #10  but this seems to be unsolved?

**Comment by geerlingguy** [comment]
Interestingly, I'm also getting a CI idempotence failure on Debian 12 (and only Debian 12...):

https://github.com/geerlingguy/ansible-role-ntp/actions/runs/7649697033/job/20844537505#step:5:212

**Comment by szEvEz** [comment]
Not sure if this is related, but on Debian Bookworm the ntp config file is now located at

`/etc/ntpsec/ntp.conf` and not `/etc/ntp.conf`

**Comment by geerlingguy** [comment]
https://github.com/geerlingguy/ansible-role-ntp/pull/130 may fix this — going to test again soon.

**Comment by geerlingguy** [comment]
I believe this is fixed now. Please let me know if not, and we can take another look.

**Comment by sylbal** [comment]
Hi,
I updated to version 2.5.0

I seem to have the same behaviour on one debian12 instance

```
ls -l /etc/localtime
lrwxrwxrwx 1 root root 34 Jul 21 14:34 /etc/localtime -> ../usr/share/zoneinfo/Europe/Paris
cat /etc/timezone
Etc/UTC
date
Mon Jul 22 08:45:27 CEST 2024
```

And on some other D12 instances the timezone is not configured at all, it stays on UTC, did not have time to investigate this second point at the moment to give more information.
