### ISSUE TITLE
Conflict with chronyd with CentOS 7

### ISSUE THREAD

**Issue by brentg71** [geerlingguy/ansible-role-ntp#22]
Sorry, I'm not too certain if this is a reasonable request or not... anyway, whenever I use this role to set up a CentOS 7 system, ntpd fails to start because, by default, chronyd is enabled (and I would rather still use ntp). Do you have any plans to add functionality that would disable chronyd? Or is this beyond the scope of your role?

**Comment by geerlingguy** [comment]
@brentg71 - Interesting... I am using this on some CentOS 7 servers without an issue, maybe this is in a certain flavor of CentOS? I'm using it with a minimal install.

The automated tests are also passing on CentOS 7: https://travis-ci.org/geerlingguy/ansible-role-ntp/jobs/217686882

**Comment by brentg71** [comment]
Thanks very much for the response! I will see if I can reproduce the error. Most likely the flavor was a qcow2 image built for OpenStack? Maybe there's something custom configured here - in which case, please disregard everything! More info to follow.

**Comment by selyx** [comment]
If you enable "network time" during the CentOS 7 installation chronyd will be used instead of ntpd (since RedHat replaced ntpd on EL7 with chronyd). Would it maybe make sense to introduce a variable to choose your prefered ntp daemon?

**Comment by selyx** [comment]
I've created PR #43 which configures chronyd instead of ntpd on RHEL / CentOS 7.

**Comment by m8ram** [comment]
chrony is the recommended package in Centos/RHEL 7.

**Comment by m8ram** [comment]
> @brentg71 - Interesting... I am using this on some CentOS 7 servers without an issue, maybe this is in a certain flavor of CentOS? I'm using it with a minimal install.
> 
> The automated tests are also passing on CentOS 7: https://travis-ci.org/geerlingguy/ansible-role-ntp/jobs/217686882

The reason the role works on a minimal install is that neither chronyd norr NTP are installed.
@brentg71 probably has installed chronyd before running this role.

**Comment by geerlingguy** [comment]
Ah, makes sense. I haven't decided yet if I'm going to try to change this role to configure `chrony` or `ntp` (that adds significant complexity because there are some differences and I would have to choose a default (and set that default) per OS). Other option is to have a separate role for `chrony`.

**Comment by geerlingguy** [comment]
See https://github.com/geerlingguy/ansible-role-ntp/pull/72#issuecomment-604508521 — this role now defaults to `chrony` for CentOS 7 and later (but you can still use `ntp` on CentOS 7 if you desire).
