### ISSUE TITLE
Question: No support for Fedora / dnf? 

### ISSUE THREAD

**Issue by schafdog** [geerlingguy/ansible-role-ntp#25]
Hi 

New to Ansible (coming from puppet) and thus also to this module.  Trying to do a debian Stretch and Fedora 25 of ntp using this module.  However getting an error when doing the F25:

fatal: [nuc.schafroth]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to nuc.schafroth closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_gaZGxt/ansible_module_yum.py\", line 25, in <module>\r\n    import yum\r\nImportError: No module named yum\r\n", "msg": "MODULE FAILURE"}

I can't find any reference to yum in the module itself, and since install using package did seem to work, I am wondering what I could be doing wrong

And I did see that Fedora is not listed in OSes.

**Comment by kadecole** [comment]
It looks like Fedora has moved from yum to dnf as package manager as of Fedora 22. 
https://www.linux.com/learn/what-you-need-know-about-fedoras-switch-yum-dnf

The roll will need updated to support newer versions of Fedora.

**Comment by geerlingguy** [comment]
@kadecole - in this case, it looks like the role should be fine (https://github.com/geerlingguy/ansible-role-ntp/blob/master/tasks/main.yml#L21) — Ansible's `package` module abstracts the package manager, and should work with `yum`, `dnf`, `apt`, `pacman`, etc.

@schafdog - What version of Ansible are you running? (`ansible --version`).

**Comment by schafdog** [comment]
Fedora 25 has ansible 2.2.1.0, which I believe is good enough for package. Again I used package to install ntp directly, but was hit by the different service name. When I found this role. 

That was also my observation that this role is fine given that it uses package. I think I am using it wrong.  Does anybody have a simple working playbook using this role I could try?

**Comment by geerlingguy** [comment]
I'm running some tests with this role's test playbook on Fedora 24, at least... and it seems like Fedora 24 passes (DNF was default as of Fedora 22).

See: https://travis-ci.org/geerlingguy/ansible-role-ntp/jobs/219442107 (part of this run: https://travis-ci.org/geerlingguy/ansible-role-ntp/builds/219442101 - debian8 is not yet passing).
