### ISSUE TITLE
Failure to change timezone on geerlingguy/docker-ubuntu1604-ansible

### ISSUE THREAD

**Issue by cwardgar** [geerlingguy/ansible-role-ntp#33]
This role, when applied to your ubuntu1604 Docker container, completes successfully but doesn't actually change the time zone. To reproduce, simply choose a non-default timezone (I used `ntp_timezone: 'America/Denver'`), login to the container, and run `date`.
```
root@54e6e2583399:/etc# date
Fri Jun  9 03:07:03 UTC 2017
```
The problem is the `/etc/localtime` symlink that the role creates:
```
lrwxrwxrwx 1 root root     34 Jun  9 03:02 localtime -> /usr/share/zoneinfo/America/Denver
```
That's all fine, except that `/usr/share/zoneinfo` **doesn't exist**. You must first install the `tzdata` package. So, simple fix.

I don't know how many other Docker and/or VM images are affected by this. A functional test would really help here.

**Comment by geerlingguy** [comment]
Good catch! That was also breaking the `debian8` build, so ensuring it's installed fixes a few annoying issues at once.
