### ISSUE TITLE
it doesn't work as a role dependencies in another role

### ISSUE THREAD

**Issue by Raffaello** [geerlingguy/ansible-role-ntp#34]
here the error:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/ansible/roles/vendor/geerlingguy.ntp/tasks/main.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Set timezone
  ^ here


The error appears to have been in '/vagrant/ansible/roles/vendor/geerlingguy.ntp/tasks/main.yml': line 13, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Set timezone
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

this is the `meta/default.yml` e.g.:

```
---

dependencies:
  - role: geerlingguy.ntp

```

**Comment by Raffaello** [comment]
please also note:

> This module configures the timezone setting, both of the system clock and of the hardware clock. If you want to set up the NTP, use service module.

ref: https://docs.ansible.com/ansible/timezone_module.html

so it seems the timezone module is causing the issue and ntp timezone should be set up differently

**Comment by geerlingguy** [comment]
@Raffaello - NTP is being managed as a `service` here: https://github.com/geerlingguy/ansible-role-ntp/blob/master/tasks/main.yml#L17-L29

It seems to be working okay for me—can you give any more detail about how the playbook is configured, or even better a playbook/project that I could use to reproduce this issue?

**Comment by Raffaello** [comment]
@geerlingguy Hi, thank you, here extra info:

- ansible version 2.1.3.0
- OS: ubuntu 14.04.5 LTS

I spent some time and it seems ansible doesn't recognize the `timezone` module, it is only that `task` that make it failing. I tried removing the timezone task and everything was successful.

the playbook is quite simple, it using a main role and inside that role i added a dependency  on this NTP role.

```
# playbook entry point
- name: Build MyServer Service Instance
  hosts: "{{ hosts }}"

  roles:
    - role: my_server
      become: true

### role my_server (meta/defaults.yml)

---

dependencies:
  - role: geerlingguy.ntp
   
```

if i comment out the task `timezone` is working. it seems in my ansible doesn't exist/recognize the `timezone` module.

**Comment by Raffaello** [comment]
@geerlingguy The problem is a bug in ansible 2.1.3.0 version. after upgrading ansible to 2.3.1.0. The `timezone` module was found and no error has happened. 

so i am closing this issue because it was strictly relatred to an ansible bug reported also here:
https://github.com/ansible/ansible-modules-extras/pull/3572

**Comment by geerlingguy** [comment]
Great! Thanks for the follow-up.
