### ISSUE TITLE
Config failure with non-default ntp_timezone on docker-ubuntu1604-ansible

### ISSUE THREAD

**Issue by cwardgar** [geerlingguy/ansible-role-ntp#35]
After #32 was merged, I started seeing the following failure when `ntp_timezone` was set to a non-default value:
```
TASK [ansible-role-ntp : Set timezone] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error message:\nstill not desired state, though changes have made\nOther message(s):\nAdded 1 line and deleted 1 line(s) on /etc/timezone"}
```
A functional test that changes the timezone and then examines the output of `date` will produce the error on the named Docker image. I don't know what other images are affected.

I'm still new to Ansible, but this strikes me as a bug in the upstream `timezone` module. At least, I don't see anything obviously wrong with the PR. If that's the case, the best we can probably do is to revert it until upstream is fixed.

**Comment by geerlingguy** [comment]
:( — do you know if there's an upstream issue for this yet?

**Comment by jdelamar** [comment]
Oh, interestingly enough, this stopped working for me today (pretty sure it did worked yesterday as I was deploying a new cluster for my things).

Anyone knows a workaround? Using Ansible 2.3.1.0 on debian-9-stretch
