### ISSUE TITLE
Idempotence issues

### ISSUE THREAD

**Issue by jamesla** [geerlingguy/ansible-role-ntp#38]
For some reason when I provision a box the first time I run molecule idempotence (or I would imagine the second time it is provisioned) the role is not idempotent and provides the following error:

ERROR: Idempotence test failed because of the following tasks:
* [default] => geerlingguy-ntp-1.5.1 : Generate ntp.conf file

After this has happened once this role is then idempotent until the box is reprovisioned from scracth again. Any idea why this would be happening?

**Comment by geerlingguy** [comment]
@jamesla - Not sure; my own tests check idempotence by running the role twice over a bunch of different OSes: https://travis-ci.org/geerlingguy/ansible-role-ntp/builds/245382685. What OS are you finding this issue on, and what variables have you overridden from the defaults?

**Comment by jamesla** [comment]
This came right by itself, I'm not sure what it was in the end
