### ISSUE TITLE
no action detected in task

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [geerlingguy/ansible-role-ntp#40]
I am a noob in ansible land (but I like it). I'm just trying to set up a simple app server. Got to the point of running my playbook, which has been used in a deploy before except for minor edits by me.

Here's the roles in my playbook:
```
roles:
     - geerlingguy.git
     - {role: franklinkim.ufw, tags: ufw}
     - {role: franklinkim.users, tags: user }
     - franklinkim.sudo
     - {role: zzet.rbenv, become: yes, tags: rbenv}
     - geerlingguy.nodejs
     - {role: geerlingguy.passenger, tags: nginx}
     - {role: ANXS.postgresql, tags: pg}
     - geerlingguy.ntp
     - nickjj.fail2ban
     - kamaln7.swapfile
```
here's the error:
```
[WARNING]: While constructing a mapping from /home/mark/Documents/work/klinikker-
KDK_V2/klinikker/provisioning/group_vars/klinikker.yml, line 2, column 1, found a duplicate dict key (apt_upgrade).  Using last
defined value only.

ERROR! no action detected in task

The error appears to have been in '/etc/ansible/roles/geerlingguy.ntp/tasks/main.yml': line 19, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Set timezone
  ^ here

```

Looking at main.yml I can't tell if it's incorrect or not. I doubt it.

**Comment by mark-jordanovic-lewis** [comment]
After having a think it's likely that ntp_timezone is not be set. So perhaps this is not an actual issue with the role. I'd still like some advice on how to deal with this, though.

**Comment by geerlingguy** [comment]
That task is: https://github.com/geerlingguy/ansible-role-ntp/blob/master/tasks/main.yml#L19-L21

I'm guessing you may be running an older version of Ansible (`ansible --version` to check) which doesn't have the `timezone` module? This role requires I think 2.2 or later.

**Comment by geerlingguy** [comment]
@xamanu - Ansible 2.3 likely doesn't work with `include_tasks`? That's my best guess. Also, to that original issue I noticed `found a duplicate dict key (apt_upgrade).` in there, maybe that was an issue elsewhere in the playbook?

Regardless, marking this as closed, can't reproduce.
