### ISSUE TITLE
Typo in ntp_servers array

### ISSUE THREAD

**Issue by codeyy** [geerlingguy/ansible-role-ntp#42]
ntp_servers:
  - "0{{ ntp_area }}.pool.ntp.org iburst"
  - "1{{ ntp_area }}.pool.ntp.org iburst"
  - "2{{ ntp_area }}.pool.ntp.org iburst"
  - "3{{ ntp_area }}.pool.ntp.org iburst"

should be:

ntp_servers:
  - "0.{{ ntp_area }}.pool.ntp.org iburst"
  - "1.{{ ntp_area }}.pool.ntp.org iburst"
  - "2.{{ ntp_area }}.pool.ntp.org iburst"
  - "3.{{ ntp_area }}.pool.ntp.org iburst"

See : http://support.ntp.org/bin/view/Servers/NTPPoolServers

**Comment by kadecole** [comment]
This is fixed in PR #41. Just waiting for review and merge.

**Comment by selyx** [comment]
The proposed solution actually breaks the ntp configuration if ntp_area is empty (which it is by default).

**Comment by ssaarinen** [comment]
This can be worked around by using eg. ntp_area = ".fi" as ntp_area is not used anywhere else afaik.
