### ISSUE TITLE
Does not update apt cache

### ISSUE THREAD

**Issue by lazzurs** [geerlingguy/ansible-role-ntp#45]
If this module is run on a server with an out of date apt cache it will fail to install the ntp package.

**Comment by evolic** [comment]
@geerlingguy I am experiencing the same issue under Ubuntu 16.04

**Comment by evolic** [comment]
```
TASK [geerlingguy.ntp : Ensure NTP-related packages are installed.] ************
```
fatal: [rabbitmq37x]: FAILED! => {"cache_update_time": 1514183524, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'ntp'' failed: E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/n/ntp/ntp_4.2.8p4+dfsg-3ubuntu5.7_amd64.deb  404  Not Found [IP: 91.189.91.26 80]\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/n/ntp/ntp_4.2.8p4+dfsg-3ubuntu5.7_amd64.deb  404  Not Found [IP: 91.189.91.26 80]\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/n/ntp/ntp_4.2.8p4+dfsg-3ubuntu5.7_amd64.deb  404  Not Found [IP: 91.189.91.26 80]", "", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  libyaml-0-2 python-cffi-backend python-crypto python-cryptography\n  python-ecdsa python-enum34 python-httplib2 python-idna python-ipaddress\n  python-jinja2 python-markupsafe python-paramiko python-pkg-resources\n  python-pyasn1 python-setuptools python-six python-yaml sshpass\nUse 'sudo apt autoremove' to remove them.\nThe following additional packages will be installed:\n  libopts25\nSuggested packages:\n  ntp-doc\nThe following NEW packages will be installed:\n  libopts25 ntp\n0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.\nNeed to get 576 kB of archives.\nAfter this operation, 1792 kB of additional disk space will be used.\nGet:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libopts25 amd64 1:5.18.7-3 [57.8 kB]\nErr:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ntp amd64 1:4.2.8p4+dfsg-3ubuntu5.7\n  404  Not Found [IP: 91.189.91.26 80]\nFetched 57.8 kB in 0s (85.2 kB/s)\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  libyaml-0-2 python-cffi-backend python-crypto python-cryptography", "  python-ecdsa python-enum34 python-httplib2 python-idna python-ipaddress", "  python-jinja2 python-markupsafe python-paramiko python-pkg-resources", "  python-pyasn1 python-setuptools python-six python-yaml sshpass", "Use 'sudo apt autoremove' to remove them.", "The following additional packages will be installed:", "  libopts25", "Suggested packages:", "  ntp-doc", "The following NEW packages will be installed:", "  libopts25 ntp", "0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.", "Need to get 576 kB of archives.", "After this operation, 1792 kB of additional disk space will be used.", "Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libopts25 amd64 1:5.18.7-3 [57.8 kB]", "Err:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ntp amd64 1:4.2.8p4+dfsg-3ubuntu5.7", "  404  Not Found [IP: 91.189.91.26 80]", "Fetched 57.8 kB in 0s (85.2 kB/s)"]}

**Comment by Papy-Bretzel** [comment]
Hi. Same bug here from a Vagrant box ("ubuntu/bionic64"). 
Adding an extra step updating apt cache before running the role fix the issue.

**Comment by lazzurs** [comment]
@geerlingguy how would you like this resolved? I figure one of the two options.

1. Update the docs to tell people that apt update is not something this role handles and it is assumed your apt cache is up to date.

2. Add the apt update to the role.

I figure 1 works better for most cases and reflects what is in the tests.

**Comment by geerlingguy** [comment]
This is the case for all my roles, and I generally recommend people handle things like outdated apt package caches in their playbooks instead of having each and every role that manages an apt package manage the cache as well. That way you can deal with your own apt cache lifecycle (how often to update, etc.).

Closing this issue as won't fix, please add a task like the following in any playbook where you need to ensure apt caches are updated (see this role's test playbook, too: https://github.com/geerlingguy/ansible-role-ntp/blob/master/molecule/default/playbook.yml#L10-L15):

```yaml
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
```
