### ISSUE TITLE
default value of ntp_timezone should be Etc/UTC

### ISSUE THREAD

**Issue by marji** [geerlingguy/ansible-role-ntp#7]
The default value for the `ntp_timezone` variable is set to America/Chicago in [defaults/main.yml](https://github.com/geerlingguy/ansible-role-ntp/blob/1420529abcdda64e1f63df142d3b99e71abf43ed/defaults/main.yml#L3).

I would suggest using `ntp_timezone: Etc/UTC` as the default.

Etc/UTC is the default value for most server installations (et least for official Ubuntu images in AWS, also Rackspace and Linode Ubuntu installations) .
IMHO, Etc/UTC is also the most frequently used value from global point of view (a sysadmin having servers in multiple timezones).

**Comment by kadecole** [comment]
We discussed this a little during the last PR. I agree this is probably the best most universal setting for the default. I would recommend this change.

**Comment by geerlingguy** [comment]
Ditto. I was being quite midwest-US-centric in my default, but to be fair, I started the role for myself and never thought about other's needs :D

**Comment by geerlingguy** [comment]
Fixed by #9.

**Comment by geerlingguy** [comment]
No longer 🇺🇸 -centric!

**Comment by geerlingguy** [comment]
And of course I forgot to close this issue... so closing it now, on the US Independence Day :)
