### ISSUE TITLE
unnecessary variable definiton for redhat

### ISSUE THREAD

**Issue by vmpr** [geerlingguy/ansible-role-ntp#80]
Hi Jeff, thanks for your hard work and maintaining so many ansible roles!

I found something in this role, one variable ( ntp_driftfile ) is not necessary in RedHat.yml:

```
cat roles/galaxy/geerlingguy.ntp/vars/RedHat.yml
---
__ntp_daemon: chronyd
ntp_tzdata_package: tzdata
__ntp_package: chrony
__ntp_config_file: /etc/chrony.conf
ntp_driftfile: /var/lib/ntp/drift
ntp_cron_daemon: crond
```
For Redhat 7+ is only chrony relevant and in the chrony template file there is no variable "ntp_driftfile" :

```
cat roles/galaxy/geerlingguy.ntp/templates/chrony.conf.j2
...
# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift
...
```
it would also has the wrong value :)

I am happy to do a PR if we are on the same page?
thanks!

**Comment by vmpr** [comment]
I would like to fix that issue for everyone, will you merge a PR? I know everyone is busy especially with all your youtube recording, but three issues I've filed just got staled - would be nice to fix them!

**Comment by vmpr** [comment]
I would like to fix that issue for everyone, will you merge a PR? I know everyone is busy especially with all your youtube recording, but three issues I've filed just got staled - would be nice to fix them!

**Comment by vmpr** [comment]
again, happy to fix that if u find time to answer @geerlingguy

**Comment by geerlingguy** [comment]
If you would like to file a PR that works on RHEL and doesn't break existing installs on other platforms I'd be willing to take a look. Sorry for the delays :)
