### ISSUE TITLE
fatal: [server]: FAILED! => {"changed": false, "msg": "No package matching 'ntp' is available"}

### ISSUE THREAD

**Issue by RafaelMiquelino** [geerlingguy/ansible-role-ntp#83]
Hi, I got the following error message when using this role:
```
TASK [geerlingguy.ntp : Ensure NTP package is installed.] *********************************************************************************************************************************************************
fatal: [server]: FAILED! => {"changed": false, "msg": "No package matching 'ntp' is available"}
```
I solved that by manually updating the package manager cache with the `apt update` command. However should it be done as part of the role?
I know we can automatically do that by passing `update_cache: yes` to the module `apt` but not sure how to manage that with the general package manager module that you are using.

**Comment by gianmarcomurru** [comment]
This happened to me too.. 

I solve it just by adding this code (that is also in ansible-role-ntp/molecule/default/converge.yml)

`- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 600
  when: ansible_os_family == 'Debian'`

on top of ansible-roles-ntp/tasks/main.yaml.

**Comment by RafaelMiquelino** [comment]
That would work for my specific case but I’m not sure if that could be the solution as this is only applicable when the `apt` package manager is used.

________________________________
